//line :1
//go:build windows

package NJ4MerJ

const (
	SC_MANAGER_CONNECT	= 1
	SC_MANAGER_CREATE_SERVICE	= 2
	SC_MANAGER_ENUMERATE_SERVICE	= 4
	SC_MANAGER_LOCK	= 8
	SC_MANAGER_QUERY_LOCK_STATUS	= 16
	SC_MANAGER_MODIFY_BOOT_CONFIG	= 32
	SC_MANAGER_ALL_ACCESS	= 0xf003f
)

const (
	SERVICE_KERNEL_DRIVER	= 1
	SERVICE_FILE_SYSTEM_DRIVER	= 2
	SERVICE_ADAPTER	= 4
	SERVICE_RECOGNIZER_DRIVER	= 8
	SERVICE_WIN32_OWN_PROCESS	= 16
	SERVICE_WIN32_SHARE_PROCESS	= 32
	SERVICE_WIN32	= SERVICE_WIN32_OWN_PROCESS | SERVICE_WIN32_SHARE_PROCESS
	SERVICE_INTERACTIVE_PROCESS	= 256
	SERVICE_DRIVER	= SERVICE_KERNEL_DRIVER | SERVICE_FILE_SYSTEM_DRIVER | SERVICE_RECOGNIZER_DRIVER
	SERVICE_TYPE_ALL	= SERVICE_WIN32 | SERVICE_ADAPTER | SERVICE_DRIVER | SERVICE_INTERACTIVE_PROCESS

	SERVICE_BOOT_START	= 0
	SERVICE_SYSTEM_START	= 1
	SERVICE_AUTO_START	= 2
	SERVICE_DEMAND_START	= 3
	SERVICE_DISABLED	= 4

	SERVICE_ERROR_IGNORE	= 0
	SERVICE_ERROR_NORMAL	= 1
	SERVICE_ERROR_SEVERE	= 2
	SERVICE_ERROR_CRITICAL	= 3

	SC_STATUS_PROCESS_INFO	= 0

	SC_ACTION_NONE	= 0
	SC_ACTION_RESTART	= 1
	SC_ACTION_REBOOT	= 2
	SC_ACTION_RUN_COMMAND	= 3

	SERVICE_STOPPED	= 1
	SERVICE_START_PENDING	= 2
	SERVICE_STOP_PENDING	= 3
	SERVICE_RUNNING	= 4
	SERVICE_CONTINUE_PENDING	= 5
	SERVICE_PAUSE_PENDING	= 6
	SERVICE_PAUSED	= 7
	SERVICE_NO_CHANGE	= 0xffffffff

	SERVICE_ACCEPT_STOP	= 1
	SERVICE_ACCEPT_PAUSE_CONTINUE	= 2
	SERVICE_ACCEPT_SHUTDOWN	= 4
	SERVICE_ACCEPT_PARAMCHANGE	= 8
	SERVICE_ACCEPT_NETBINDCHANGE	= 16
	SERVICE_ACCEPT_HARDWAREPROFILECHANGE	= 32
	SERVICE_ACCEPT_POWEREVENT	= 64
	SERVICE_ACCEPT_SESSIONCHANGE	= 128
	SERVICE_ACCEPT_PRESHUTDOWN	= 256

	SERVICE_CONTROL_STOP	= 1
	SERVICE_CONTROL_PAUSE	= 2
	SERVICE_CONTROL_CONTINUE	= 3
	SERVICE_CONTROL_INTERROGATE	= 4
	SERVICE_CONTROL_SHUTDOWN	= 5
	SERVICE_CONTROL_PARAMCHANGE	= 6
	SERVICE_CONTROL_NETBINDADD	= 7
	SERVICE_CONTROL_NETBINDREMOVE	= 8
	SERVICE_CONTROL_NETBINDENABLE	= 9
	SERVICE_CONTROL_NETBINDDISABLE	= 10
	SERVICE_CONTROL_DEVICEEVENT	= 11
	SERVICE_CONTROL_HARDWAREPROFILECHANGE	= 12
	SERVICE_CONTROL_POWEREVENT	= 13
	SERVICE_CONTROL_SESSIONCHANGE	= 14
	SERVICE_CONTROL_PRESHUTDOWN	= 15

	SERVICE_ACTIVE	= 1
	SERVICE_INACTIVE	= 2
	SERVICE_STATE_ALL	= 3

	SERVICE_QUERY_CONFIG	= 1
	SERVICE_CHANGE_CONFIG	= 2
	SERVICE_QUERY_STATUS	= 4
	SERVICE_ENUMERATE_DEPENDENTS	= 8
	SERVICE_START	= 16
	SERVICE_STOP	= 32
	SERVICE_PAUSE_CONTINUE	= 64
	SERVICE_INTERROGATE	= 128
	SERVICE_USER_DEFINED_CONTROL	= 256
	SERVICE_ALL_ACCESS	= STANDARD_RIGHTS_REQUIRED | SERVICE_QUERY_CONFIG | SERVICE_CHANGE_CONFIG | SERVICE_QUERY_STATUS | SERVICE_ENUMERATE_DEPENDENTS | SERVICE_START | SERVICE_STOP | SERVICE_PAUSE_CONTINUE | SERVICE_INTERROGATE | SERVICE_USER_DEFINED_CONTROL

	SERVICE_RUNS_IN_SYSTEM_PROCESS	= 1

	SERVICE_CONFIG_DESCRIPTION	= 1
	SERVICE_CONFIG_FAILURE_ACTIONS	= 2
	SERVICE_CONFIG_DELAYED_AUTO_START_INFO	= 3
	SERVICE_CONFIG_FAILURE_ACTIONS_FLAG	= 4
	SERVICE_CONFIG_SERVICE_SID_INFO	= 5
	SERVICE_CONFIG_REQUIRED_PRIVILEGES_INFO	= 6
	SERVICE_CONFIG_PRESHUTDOWN_INFO	= 7
	SERVICE_CONFIG_TRIGGER_INFO	= 8
	SERVICE_CONFIG_PREFERRED_NODE	= 9
	SERVICE_CONFIG_LAUNCH_PROTECTED	= 12

	SERVICE_SID_TYPE_NONE	= 0
	SERVICE_SID_TYPE_UNRESTRICTED	= 1
	SERVICE_SID_TYPE_RESTRICTED	= 2 | SERVICE_SID_TYPE_UNRESTRICTED

	SC_ENUM_PROCESS_INFO	= 0

	SERVICE_NOTIFY_STATUS_CHANGE	= 2
	SERVICE_NOTIFY_STOPPED	= 0x00000001
	SERVICE_NOTIFY_START_PENDING	= 0x00000002
	SERVICE_NOTIFY_STOP_PENDING	= 0x00000004
	SERVICE_NOTIFY_RUNNING	= 0x00000008
	SERVICE_NOTIFY_CONTINUE_PENDING	= 0x00000010
	SERVICE_NOTIFY_PAUSE_PENDING	= 0x00000020
	SERVICE_NOTIFY_PAUSED	= 0x00000040
	SERVICE_NOTIFY_CREATED	= 0x00000080
	SERVICE_NOTIFY_DELETED	= 0x00000100
	SERVICE_NOTIFY_DELETE_PENDING	= 0x00000200

	SC_EVENT_DATABASE_CHANGE	= 0
	SC_EVENT_PROPERTY_CHANGE	= 1
	SC_EVENT_STATUS_CHANGE	= 2

	SERVICE_START_REASON_DEMAND	= 0x00000001
	SERVICE_START_REASON_AUTO	= 0x00000002
	SERVICE_START_REASON_TRIGGER	= 0x00000004
	SERVICE_START_REASON_RESTART_ON_FAILURE	= 0x00000008
	SERVICE_START_REASON_DELAYEDAUTO	= 0x00000010

	SERVICE_DYNAMIC_INFORMATION_LEVEL_START_REASON	= 1
)

type OHY0gnouiRt6 struct {
	Pbk5xHqhaeu	*uint16
	Hu86SO6Hg	*uint16
	GG6SovY	YhbjUYS0
}

type YhbjUYS0 struct {
	LEAovVEv	uint32
	TvZOBpO8U0	uint32
	QMAbEFeTeD	uint32
	K6gVaYYZTn2	uint32
	CQD6CvKqUjQ	uint32
	FpAmgRdFQRz	uint32
	WEJRuW	uint32
}

type MSSmb3ckxDlt struct {
	QIXE7JyADD	*uint16
	G92hNyAf	uintptr
}

type FJRpa4YpK struct {
	FdUz_3J	uint32
	MeFSROIlad	uint32
	TuHdy5YM	uint32
	GKE_DgR	*uint16
	Ua0xNVyFP	*uint16
	DGQYbhlc7Iwy	uint32
	Qsv6wZ266Jb	*uint16
	DG5J61b9	*uint16
	HBSk9HPI	*uint16
}

type FI3QUi struct {
	CKLN_74Dw3XO *uint16
}

type GRrQ_BBM struct {
	TVnjkl5Vn uint32
}

type M_UOkIq31m struct {
	MbTEGuAK	uint32
	K9dFkP9Z	uint32
	DNiTnixrKLf	uint32
	HiqNZhv	uint32
	I6eCN8	uint32
	RKtDec	uint32
	LYmQ9fRU	uint32
	KSG894DU	uint32
	VKauXl1ayvx	uint32
}

type TxyaI6P struct {
	V5AzjYG1uuU	*uint16
	ETf_nREJSp	*uint16
	AfqaE0DAT	M_UOkIq31m
}

type S5pK5u struct {
	Lki1grRPW5	uint32
	YmPByKo	uintptr
	CvD2Ao1VKWl	uintptr
	DvrIKY6p6N3a	uint32
	A__Ns_0AC7	M_UOkIq31m
	D5WJHVn	uint32
	MSDkY0i3KB	*uint16
}

type J2AQZNWjhChJ struct {
	IWIP9F27Sc	uint32
	BAEnIMx17WN	*uint16
	E7HGE51Guw	*uint16
	L5ivf3	uint32
	UgDkxr76	*SLfb1P6TiGi
}

type JiGFtgyYZnNP struct {
	W70rev1 int32
}

type SLfb1P6TiGi struct {
	MYIMSJ7IU	uint32
	KFQKJ9tZt	uint32
}

type XoQ8Jtg struct {
	RXBlOGlUFYjC	uint32
	WWLCa_py8R	*uint16
	JbZdMlES9sWG	uint32
}
